name: Sync Upstream and Build .deb

on:
  schedule:
    - cron: "0 */6 * * *"  # Run every 6 hours
  workflow_dispatch:
    inputs:
      use_fake_tag:
        description: 'Use fake tag for testing?'
        required: false
        default: 'false'

jobs:
  sync-and-build:
    runs-on: ubuntu-latest

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
    - name: 1 - Checkout your fork
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: 2 - Add upstream remote
      run: |
        git remote add upstream https://github.com/mhx/dwarfs.git
        git fetch upstream --tags

    - name: 3 - Get latest upstream tag
      id: upstream
      run: |
        if [[ "${{ github.event.inputs.use_fake_tag }}" == "true" ]]; then
          echo "tag=testing-fake-tag" >> "$GITHUB_OUTPUT"
        else
          TAG=$(git ls-remote --tags upstream | grep -o 'refs/tags/[^{}]*$' | sort -V | tail -n1 | sed 's#refs/tags/##')
          echo "Detected upstream tag: $TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        fi
        echo "Upstream tag is ${{ steps.upstream.outputs.tag }}"

    - name: 3.5 - Resolve actual latest upstream tag
      id: resolved
      run: |
        if [ "${{ steps.upstream.outputs.tag }}" = "testing-fake-tag" ]; then
          REAL_TAG=$(git ls-remote --tags upstream | grep -o 'refs/tags/[^{}]*$' | sed 's#refs/tags/##' | sort -V | tail -n1)
          echo "resolved_tag=$REAL_TAG" >> $GITHUB_OUTPUT
        else
          echo "resolved_tag=${{ steps.upstream.outputs.tag }}" >> $GITHUB_OUTPUT
        fi
        echo "Resolved tag is ${{ steps.resolved.outputs.resolved_tag }}"

    - name: 4 - Check if tag exists locally
      id: checktag
      run: |
        if git rev-parse "refs/tags/${{ steps.resolved.outputs.resolved_tag }}" >/dev/null 2>&1; then
          echo "found=true" >> $GITHUB_OUTPUT
        else
          echo "found=false" >> $GITHUB_OUTPUT
        fi
        echo "Resolved tag is ${{ steps.resolved.outputs.resolved_tag }}"

    - name: 5 - Exit if tag already exists
      if: steps.checktag.outputs.found == 'true'
      run: |
        echo "No new upstream version. Exiting."
        exit 0
      continue-on-error: false

    - name: 6 - Fetch and checkout new upstream tag
      run: |
        echo -e "Resolved tag is ${{ steps.resolved.outputs.resolved_tag }}"
        TAG="${{ steps.resolved.outputs.resolved_tag }}"
        git fetch upstream --tags || true
        git checkout -B update-"$TAG" "upstream/$TAG" || git checkout -b update-"$TAG"

    - name: 7 - Remove upstream GitHub workflows
      run: rm -f .github/workflows/*.yml || true

    - name: 8 - Copy DEBIAN/ directory into working tree
      run: |
        git checkout origin/main -- DEBIAN

    - name: 9 - Install dependencies
      id: parsed
      run: |
        sudo apt update && sudo apt install -y devscripts debhelper dpkg-dev gnupg dput upx
        TAG="${{ steps.resolved.outputs.resolved_tag }}"
        TAG_NO_V="${TAG#v}"
        echo "tag_no_v=$TAG_NO_V" >> "$GITHUB_OUTPUT"

    - name: 10 - Download universal binary and decompress
      run: |
        TAG="${{ steps.resolved.outputs.resolved_tag }}"
        TAG_NO_V="${TAG#v}"
        echo "Resolved tag is ${{ steps.parsed.outputs.resolved_tag }} and TAG is $TAG"
        echo "Parsed tag_no_v is ${{ steps.parsed.outputs.tag_no_v }} and TAG_NO_V is $TAG_NO_V"
        URL="https://github.com/mhx/dwarfs/releases/download/${TAG}/dwarfs-universal-${TAG_NO_V}-Linux-x86_64"
        curl -L "$URL" -o dwarfs
        chmod +x dwarfs
        upx -d dwarfs || echo "Already decompressed"
        mkdir -p dwarfs-${TAG_NO_V}/usr/bin
        mv dwarfs dwarfs-${TAG_NO_V}/usr/bin/dwarfs
        chmod 755 usr/bin/dwarfs

    - name: 11 - Prepare source package
      run: |
        TAG="${{ steps.resolved.outputs.resolved_tag }}"
        TAG_NO_V="${TAG#v}"
        echo "Resolved tag is ${{ steps.parsed.outputs.resolved_tag }} and TAG is $TAG"
        echo "Parsed tag_no_v is ${{ steps.parsed.outputs.tag_no_v }} and TAG_NO_V is $TAG_NO_V"
        cd dwarfs-${TAG_NO_V}
        mkdir debian
        cat > debian/control <<EOF
Source: dwarfs
Maintainer: mhx github@mhxnet.de
Section: utils
Priority: optional
Standards-Version: 4.5.0
Build-Depends: debhelper (>= 11)

Package: dwarfs
Architecture: amd64
Depends: fuse3, \\${misc:Depends}
Description: DwarFS (Deduplicating Warp-speed Advanced Read-only File System)
 Precompiled universal binary repackaged as a Debian package.
 Includes mkdwarfs, dwarfsck, dwarfsextract, and the FUSE driver.
EOF

        cat > debian/rules <<EOF
#!/usr/bin/make -f
%:
    dh \\$@
override_dh_auto_build:
    # nothing to build
override_dh_auto_install:
    mkdir -p debian/dwarfs/usr/bin
    cp -a usr/bin/dwarfs debian/dwarfs/usr/bin/
EOF

    chmod +x debian/rules
    dch --create -v "${TAG_NO_V}" --package dwarfs "New upstream release"    # Changelog
    echo "12" > debian/compat    # Compat (if needed)

    - name: 12 - Build packages
      run: |
        TAG_NO_V="${{ steps.parsed.outputs.tag_no_v }}"
        cd dwarfs-${TAG_NO_V}

        tar czf ../dwarfs_${TAG_NO_V}.orig.tar.gz --exclude=debian --transform="s,^,dwarfs-${TAG_NO_V}/," usr        # Create .orig.tar.gz from source dir (excluding debian/)
        dpkg-source -b .        # Build source package
        dpkg-deb --build debian/dwarfs ../dwarfs_${TAG_NO_V}_amd64.deb        # Build binary .deb (for local install or testing)

    - name: 13 - Import GPG key
      run: |
        echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
        echo -e "trust\n5\ny\n" | gpg --command-fd 0 --batch --edit-key "${{ secrets.GPG_KEY_ID }}"
        echo "allow-preset-passphrase" >> ~/.gnupg/gpg-agent.conf
        echo RELOADAGENT | gpg-connect-agent
        KEYID=$(gpg --list-keys --with-colons | awk -F: '/^pub/ {print $5}' | head -n1)
        echo "$KEYID" > keyid.txt
        echo "${{ secrets.GPG_PASSPHRASE }}" | /usr/lib/gnupg/gpg-preset-passphrase --preset "$KEYID"
      env:
        GPG_TTY: ${{ runner.env.TERM }}

    - name: 14 - Sign Packages
      run: |
        debsign -k"${{ secrets.GPG_KEY_ID }}" --re-sign ../dwarfs_*.dsc
        debsign -k"${{ secrets.GPG_KEY_ID }}" --re-sign ../dwarfs_*.changes

#    - name: 14 - Configure dput
#      run: |
#          cat <<EOF > ~/.dput.cf
#          [launchpad]
#          fqdn = ppa.launchpad.net
#          incoming = ~${{ secrets.LAUNCHPAD_USERNAME }}/ubuntu/${{ secrets.LAUNCHPAD_PPA_NAME }}
#          login = anonymous
#          method = ftp
#          EOF

    - name: 15 - Upload to Launchpad
      run: |
        dput ppa:seann-giffin/dwarfs ../dwarfs_*.changes
#        CHANGES_FILE=$(ls ../*.changes | head -n1)
#        dput launchpad "$CHANGES_FILE"
